FROM mcr.microsoft.com/devcontainers/javascript-node:14
USER node
ADD --chown=node splunkbeta.tgz /opt/
RUN npx degit Bre77/splunk-dev /opt/splunkbeta/etc/apps/000_dev && npx degit ChrisYounger/config_explorer /opt/splunkbeta/etc/apps/config_explorer
VOLUME [ "/splunkbeta/splunk/etc", "/splunkbeta/splunk/var" ]
ENV SPLUNK_HOME=/opt/splunkbeta
#RUN /opt/splunkbeta/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd devcontainer && /opt/splunkbeta/bin/splunk stop
#RUN echo '\nOPTIMISTIC_ABOUT_FILE_LOCKING = 1' >> /opt/splunkbeta/etc/splunk-launch.conf
LABEL name=suidev